export const RECOMMENDATION_SEED = [
  {
    candidateId: "candidate-lina",
    name: "Lina Moreau",
    role: "Lead Data Scientist Anti-fraude",
    score: 92,
    recommendedFor: "Head of AI Risk · Direction des Risques",
    recommendedBy: "Société Générale",
    recommendedAt: "2025-10-28T09:45:00+02:00",
    status: "recommended",
    candidateNotes:
      "Lead IA ayant industrialisé 3 plateformes anti-fraude temps réel et orchestré des chantiers de remédiation KYC internationaux.",
    availability: "Disponible sous 1 mois",
    contactEmail: "lina.moreau@talents.ai",
    contactPhone: "+33 6 45 67 89 12",
    scoreDetails: [
      { label: "Matching mission", value: "96% d'adéquation sur les besoins Risk & Compliance" },
      { label: "Expertise sectorielle", value: "12 ans en IA bancaire et lutte anti-fraude" },
      { label: "Leadership", value: "Management d'équipes pluridisciplinaires (8 data scientists)" },
    ],
    offer: {
      id: "offer-head-ai-risk",
      title: "Head of AI Risk",
      team: "Direction des Risques",
      location: "Paris · Hybride",
      contractType: "CDI",
      contractDuration: "Temps plein",
      salaryRange: "90-110K€",
      mission:
        "Piloter la stratégie IA anti-fraude pour le Groupe, coordonner une squad de data scientists senior et garantir la conformité des modèles auprès des régulateurs.",
      keyPoints: [
        "Management de 8 data scientists et data engineers spécialisés KYC/Fraud",
        "Déploiement de modèles explainables dans 12 entités internationales",
        "Reporting régulateurs ACPR/EBA et animation du comité de gouvernance IA",
      ],
    },
  },
  {
    candidateId: "candidate-sarah",
    name: "Sarah Ndiaye",
    role: "Compliance Officer Senior",
    score: 85,
    recommendedFor: "Responsable Conformité Corporate · Pôle Wholesale Banking",
    recommendedBy: "Société Générale",
    recommendedAt: "2025-10-19T14:20:00+02:00",
    status: "recommended",
    candidateNotes: "Pilote des programmes de remédiation KYC sur des portefeuilles grands comptes européens.",
    availability: "Disponible immédiatement",
    contactEmail: "sarah.ndiaye@compliance.io",
    contactPhone: "+33 6 23 45 67 89",
    scoreDetails: [
      { label: "Matching mission", value: "92% sur les enjeux conformité corporate" },
      { label: "Expérience terrain", value: "6 ans de remédiation KYC grands comptes" },
      { label: "Certification", value: "Titulaire CAMS & ISO 37001" },
    ],
    offer: {
      id: "offer-compliance-corporate",
      title: "Responsable Conformité Corporate",
      team: "Wholesale Banking · Pôle conformité",
      location: "Lyon · Présentiel",
      contractType: "CDD",
      contractDuration: "12 mois",
      salaryRange: "70-80K€",
      mission:
        "Superviser la remédiation KYC corporate, piloter les plans d'actions LCB-FT et sécuriser les contrôles réglementaires pour le segment grands comptes.",
      keyPoints: [
        "Encadrement d'une équipe de 6 analystes conformité",
        "Pilotage des audits et contrôles ACPR",
        "Coordination avec les métiers Wholesale Banking sur les dossiers sensibles",
      ],
    },
  },
  {
    candidateId: "candidate-amelie-bpce",
    name: "Amélie Carpentier",
    role: "Lead UX Banking",
    score: 87,
    recommendedFor: "Lead UX Omnicanal · BPCE Digital & Payments",
    recommendedBy: "BPCE",
    recommendedAt: "2025-10-25T11:35:00+02:00",
    status: "recommended",
    candidateNotes: "Experte en conception d'expériences unifiées multi-canal avec un focus sur les parcours paiement.",
    availability: "Préavis 2 mois",
    contactEmail: "amelie.carpentier@uxlead.io",
    contactPhone: "+33 6 12 34 56 70",
    scoreDetails: [
      { label: "Matching mission", value: "90% sur la refonte UX omnicanal" },
      { label: "Expérience utilisateur", value: "10 ans sur parcours paiement et banque retail" },
      { label: "Pilotage design", value: "Animation d'une guilde de 10 designers" },
    ],
    offer: {
      id: "offer-lead-ux-omnicanal",
      title: "Lead UX Omnicanal",
      team: "BPCE Digital & Payments",
      location: "Paris · Hybride",
      contractType: "CDI",
      contractDuration: "Temps plein",
      salaryRange: "65-75K€",
      mission:
        "Concevoir la stratégie UX omnicanal pour les parcours paiement et piloter la cohérence des interfaces web/mobile avec les standards BPCE.",
      keyPoints: [
        "Animation d'une guilde de 10 designers et chercheurs",
        "Mise en place de design systems compatibles avec 4 marques du Groupe",
        "Mesure de l'expérience utilisateur via analytics et test & learn",
      ],
    },
  },
  {
    candidateId: "candidate-thomas-bpce",
    name: "Thomas Garnier",
    role: "Responsable Data Engineering",
    score: 89,
    recommendedFor: "Head of Data Platform · BPCE SI",
    recommendedBy: "BPCE",
    recommendedAt: "2025-10-17T16:10:00+02:00",
    status: "recommended",
    candidateNotes: "Construit des plateformes data temps réel à l'échelle groupe, expertise forte sur la gouvernance et la fiabilité.",
    availability: "Disponible sous 3 mois",
    contactEmail: "thomas.garnier@datalead.io",
    contactPhone: "+33 6 98 76 54 32",
    scoreDetails: [
      { label: "Matching mission", value: "94% pour la construction de plateformes data" },
      { label: "Architecture", value: "Migration data mesh multi-cloud finalisée" },
      { label: "Gouvernance", value: "Mise en place d'indicateurs qualité et SLA" },
    ],
    offer: {
      id: "offer-head-data-platform",
      title: "Head of Data Platform",
      team: "BPCE Systèmes d'Information",
      location: "Nantes · Hybride",
      contractType: "CDI",
      contractDuration: "Temps plein",
      salaryRange: "85-95K€",
      mission:
        "Structurer la plateforme data Groupe, industrialiser les pipelines temps réel et garantir la conformité des données exposées.",
      keyPoints: [
        "Management de 12 data engineers et SRE",
        "Migration vers une architecture data mesh multi-cloud",
        "Mise en place d'indicateurs qualité et SLA data pour les métiers",
      ],
    },
  },
]
